import { env } from 'cloudflare:workers';

export type LeadInput={businessName:string;placeId?:string;mapsUrl?:string;websites?:string[];phones?:string[];whatsapps?:string[];emails?:string[];rating?:number|null;reviewCount?:number;fullAddress:string;country:string;state:string;city:string;category:string;status?:string;confidence?:string};
const table=`CREATE TABLE IF NOT EXISTS leads (id INTEGER PRIMARY KEY AUTOINCREMENT,business_name TEXT NOT NULL,place_id TEXT,maps_url TEXT,websites TEXT NOT NULL DEFAULT '[]',phones TEXT NOT NULL DEFAULT '[]',whatsapps TEXT NOT NULL DEFAULT '[]',emails TEXT NOT NULL DEFAULT '[]',rating REAL,review_count INTEGER NOT NULL DEFAULT 0,full_address TEXT NOT NULL,country TEXT NOT NULL,state TEXT NOT NULL,city TEXT NOT NULL,category TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Collected',confidence TEXT NOT NULL DEFAULT 'Medium',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`;
let initialized=false;
export async function db(){if(!initialized){await env.DB.prepare(table).run();await env.DB.prepare('CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_identity ON leads (business_name, full_address)').run();await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_leads_created ON leads (created_at)').run();initialized=true}return env.DB}
export async function saveLead(l:LeadInput){const d=await db(),now=new Date().toISOString();await d.prepare(`INSERT INTO leads (business_name,place_id,maps_url,websites,phones,whatsapps,emails,rating,review_count,full_address,country,state,city,category,status,confidence,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(business_name,full_address) DO UPDATE SET maps_url=excluded.maps_url,websites=excluded.websites,phones=excluded.phones,whatsapps=excluded.whatsapps,emails=excluded.emails,rating=excluded.rating,review_count=excluded.review_count,status=excluded.status,confidence=excluded.confidence,updated_at=excluded.updated_at`).bind(l.businessName,l.placeId||null,l.mapsUrl||null,JSON.stringify(l.websites||[]),JSON.stringify(l.phones||[]),JSON.stringify(l.whatsapps||[]),JSON.stringify(l.emails||[]),l.rating??null,l.reviewCount||0,l.fullAddress,l.country,l.state,l.city,l.category,l.status||'Collected',l.confidence||'Medium',now,now).run()}
export function output(r:Record<string,unknown>){return {id:r.id,businessName:r.business_name,mapsUrl:r.maps_url,websites:JSON.parse(String(r.websites||'[]')),phones:JSON.parse(String(r.phones||'[]')),whatsapps:JSON.parse(String(r.whatsapps||'[]')),emails:JSON.parse(String(r.emails||'[]')),rating:r.rating,reviewCount:r.review_count,fullAddress:r.full_address,country:r.country,state:r.state,city:r.city,category:r.category,status:r.status,confidence:r.confidence,createdAt:r.created_at}}
export async function list(u:URL){const d=await db(),q=u.searchParams.get('q')||'',status=u.searchParams.get('status')||'all',from=u.searchParams.get('from')||'',to=u.searchParams.get('to')||'';let sql='SELECT * FROM leads WHERE 1=1',args:unknown[]=[];if(q){sql+=' AND (business_name LIKE ? OR category LIKE ? OR city LIKE ?)';args.push(`%${q}%`,`%${q}%`,`%${q}%`)}if(status!=='all'){sql+=' AND status=?';args.push(status)}if(from){sql+=' AND created_at>=?';args.push(from)}if(to){sql+=' AND created_at<?';args.push(to+'T23:59:59.999Z')}sql+=' ORDER BY created_at DESC LIMIT 1000';const rows=await d.prepare(sql).bind(...args).all();return rows.results.map(x=>output(x as Record<string,unknown>))}
export async function removeLead(id?:number){const d=await db();if(id){const result=await d.prepare('DELETE FROM leads WHERE id=?').bind(id).run();return result.meta.changes||0}const result=await d.prepare('DELETE FROM leads').run();return result.meta.changes||0}
